spring.application.name=Hariom_Ind
server.port=8090

spring.datasource.url=jdbc:mariadb://localhost:3306/hari_om
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

jwt.secret=MySecretKeyMySecretKeyMySecretKey12345
jwt.expiration=60
